
language: node_js

node_js:
  - "6"

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3 # give xvfb some time to start

after_success:
  # - cat ./coverage/*/lcov.info | ./node_modules/coveralls/bin/coveralls.js
  - ./shell/gh-pages.sh

before_install:
  - openssl aes-256-cbc -K $encrypted_7c71e0dd5cbb_key -iv $encrypted_7c71e0dd5cbb_iv -in yad3w.enc -out yad3w -d
